[theme]
base = "light"
primaryColor = "#109B78"
backgroundColor = "#F2F6F1"
secondaryBackgroundColor = "#FFFDF8"
textColor = "#15342D"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
